[{"name": "test.test_protein_to_random_rna.TestProteinToRandomRNA.test_first", "status": "failed", "message": "src.protein_to_random_rna.ProteinToRandomRNA does not exist!", "passed": false, "points": ["p07-08.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e08_protein_to_random_rna/test/test_protein_to_random_rna.py\", line 25, in test_first\n    p=ProteinToRandomRNA()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e08_protein_to_random_rna/tmc/utils.py\", line 10, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_protein_to_random_rna.TestProteinToRandomRNA.test_random", "status": "failed", "message": "src.protein_to_random_rna.ProteinToRandomRNA does not exist!", "passed": false, "points": ["p07-08.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e08_protein_to_random_rna/test/test_protein_to_random_rna.py\", line 30, in test_random\n    p=ProteinToRandomRNA()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e08_protein_to_random_rna/tmc/utils.py\", line 10, in fail\n    raise AssertionError(err)\n"]}]