[{"name": "test.test_markov_chain_log_probability.TestMarkovChainLogProbability.test_first", "status": "failed", "message": "0.0 != -31.71783 within 5 places", "passed": false, "points": ["p07-15.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e15_markov_chain_log_probability/test/test_markov_chain_log_probability.py\", line 45, in test_first\n    self.assertAlmostEqual(prob, -3.171783e+01, places=5)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_markov_chain_log_probability.TestMarkovChainLogProbability.test_random", "status": "passed", "message": "", "passed": true, "points": ["p07-15.1"], "backtrace": []}, {"name": "test.test_markov_chain_log_probability.TestMarkovChainLogProbability.test_uniform", "status": "failed", "message": "0.0 != -8 within 7 places", "passed": false, "points": ["p07-15.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e15_markov_chain_log_probability/test/test_markov_chain_log_probability.py\", line 67, in test_uniform\n    self.assertAlmostEqual(mc.log_probability(kmer), -2*n)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}]