[{"name": "test.test_missing_value_types.MissingValueTypes.test_columns", "status": "errored", "message": "'NoneType' object has no attribute 'columns'", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 31, in test_columns\n    np.testing.assert_array_equal(df.columns, [\"Year of independence\", \"President\"],\n"]}, {"name": "test.test_missing_value_types.MissingValueTypes.test_dtypes", "status": "errored", "message": "'NoneType' object has no attribute 'dtypes'", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 36, in test_dtypes\n    self.assertEqual(df.dtypes[0], np.float64, msg=\"Incorrect type in column 0!\")\n"]}, {"name": "test.test_missing_value_types.MissingValueTypes.test_index", "status": "errored", "message": "'NoneType' object has no attribute 'index'", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 26, in test_index\n    np.testing.assert_array_equal(df.index, [\"United Kingdom\",\"Finland\", \"USA\",\"Sweden\",\"Germany\",\"Russia\"],\n"]}, {"name": "test.test_missing_value_types.MissingValueTypes.test_nan", "status": "errored", "message": "'NoneType' object has no attribute 'isnull'", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 41, in test_nan\n    m = df.isnull().values\n"]}, {"name": "test.test_missing_value_types.MissingValueTypes.test_shape", "status": "errored", "message": "'NoneType' object has no attribute 'shape'", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 22, in test_shape\n    self.assertEqual(df.shape, (6,2), msg=\"Incorrect shape!\")\n"]}]